### ISSUE TITLE
Solr Version mismatch

### ISSUE THREAD

**Issue by sanfordd** [curationexperts/ansible-hydra#100]
There's a mismatch between the solr roles during the install and the in the template configuration file.
/roles/hydra-stack/install/templates/hydra_xml.j2  is listed as 4.10.3
The solr_version variable in /roles/hydra-stack/install/defaults/main.yml is listed as 4.10.4

**Comment by acozine** [comment]
Thanks for pointing this out. Fixed by 1cad437ec7fea83b42977a502352048c56a0d5dc.
