### ISSUE TITLE
Vagrant deployment fails at "housekeeping | format volume for /opt" with "Device /dev/xvdf not found"

### ISSUE THREAD

**Issue by erickpeirson** [curationexperts/ansible-hydra#11]
I tried deploying in Vagrant using your sample Vagrantfile. It all got off to a great start, but went off the rails when it got to the task: `housekeeping | format volume for /opt`. 

``` shell
TASK: [housekeeping | format volume for /opt] *********************************
failed: [default] => {"failed": true}
msg: Device /dev/xvdf not found.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
          to retry, use: --limit @/Users/erickpeirson/vagrant.retry

default                    : ok=4    changed=2    unreachable=0    failed=1  

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

The entire Vagrant output is [here](http://pastebin.com/qGxfEM44). 

Vagrant 1.7.4
Ansible 1.9.3

**Comment by acozine** [comment]
Ah, this is a place where Vagrant and AWS diverge - the scripts expect a disk at /dev/xvdf to mount at /opt (on EC2 this setup makes backups and upgrades easy). When I updated the Vagrantfile to create and attach a disk, I discovered that Vagrant/VirtualBox adds it at /dev/sdb. 

I put a fix in a branch called “vagrant” - can you clone the branch, update your Vagrantfile, and try again?

**Comment by erickpeirson** [comment]
Cool! That seems to have take care of the issue; everything deployed and so far seems to be running. Thanks!

However, I am running into an error with Solr, which may or may not be outside of the scope of this project:

When I attempt to access http://localhost:2424/hydra/, I get this error:

```
HTTP Status 500 - {msg=SolrCore 'collection1' is not available due to init failure: Could not load conf for core collection1: Error loading solr config from /opt/solr/collection1/conf/solrconfig.xml,trace=org.apache.solr.common.SolrException: SolrCore 'collection1' is not available due to init failure: Could not load conf for core collection1: Error loading solr config from /opt/solr/collection1/conf/solrconfig.xml at ...
```

(full output [here](http://pastebin.com/RD8P9qbL))

I checked `/opt/solr` and children, and tomcat7 seems to have r+w access to everything. But I do notice that two symlinks in `/opt/solr/collection1/conf` appear to be broken: 
- `schema.xml -> /opt/sufia-project/current/solr_conf/conf/schema.xml`
- `solrconfig.xml -> /opt/sufia-project/current/solr_conf/conf/solrconfig.xml`

`/opt/sufia-project/current` doesn't exist.

But again, maybe outside the scope of this project. Feel free to disregard. :-)

_edit: typo_

**Comment by erickpeirson** [comment]
Replacing the broken symlinks with `/opt/install/solr-4.10.3/example/solr/collection1/conf/schema.xml` and `solrconfig.xml` solved the problem.

**Comment by acozine** [comment]
Thanks for testing and for providing feedback! 

The Ansible scripts put symlinks in place for the schema.xml and solrconfig.xml files. If you deploy with Capistrano to the expected directory (/opt/sufia-project/current) those files get placed where the symlinks expect them. Once the code is in place, you need to restart Tomcat, then restart Apache. This is the primary reason I’d like to recreate the Capistrano functionality in Ansible, to make the entire process run with a single command.

**Comment by erickpeirson** [comment]
See, this is what happens when I don't read documentation carefully.

Thanks for your help!

---

Erick Peirson
Postdoctoral Scholar
ASU-SFI Center for Biosocial Complexity
Arizona State University
