### ISSUE TITLE
Postgres Version Error

### ISSUE THREAD

**Issue by sanfordd** [curationexperts/ansible-hydra#117]
The current version of Postgres '9.4' in
/roles/sufia_dependencies/install/defaults/main.yml
causes an error when installing with Ubuntu  (14.04)
The current package version in the repos for Ubuntu is 9.3

When the handler "configure md5 security"
/roles/sufia_dependencies/install/handlers/main.yml
is triggered, it errors out since it can't find the path to version 9.4

**Comment by acozine** [comment]
Addressed by #121. @sanfordd can you confirm?

**Comment by sanfordd** [comment]
@acozine It's confirmed, a test run didn't generate any errors on the install.
