### ISSUE TITLE
Solr Version limit

### ISSUE THREAD

**Issue by sanfordd** [curationexperts/ansible-hydra#132]
The current solr version regex check in roles/hydra-stack/install/tasks/main.yml fails under double digit version numbers. 
An improved version would be
solr_version | match("^5.\d{1,2}.\d{1,2}")
solr_version | match("^4.\d{1,2}.\d{1,2}")
That should catch double digit versions of 4.10 and any future cases where they end up going that high.

**Comment by acozine** [comment]
Closed by 65ddc0da9e5ed0c0fc2fcaf472825d6e9d32131e.
