### ISSUE TITLE
`centos` branch points to a single libpng source forge mirror

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#149]
The task to install the libpng libraries points to a single SourceForge mirror (superb-sea2.dl) which is not responding this morning:
https://github.com/curationexperts/ansible-hydra/blob/centos/roles/imagemagick/tasks/libpng.yml#L3

```
get_url: url=http://superb-sea2.dl.sourceforge.net/project/libpng/libpng16/{{ libpng_ver }}/libpng-{{ libpng_ver }}.tar.gz dest={{ magick_path }}/libpng-{{ libpng_ver }}.tar.gz
```

It looks like master just points to the main site and follows the redirect for any appropriate mirror, so I reverted to this and things ran successfully

```
get_url: url=http://sourceforge.net/projects/libpng/files/libpng16/{{ libpng_ver }}/libpng-{{ libpng_ver }}.tar.gz dest={{ magick_path }}/libpng-{{ libpng_ver }}.tar.gz
```

**Comment by mark-dce** [comment]
Actually when I ran, I pointed at `downloads.sourceforge.net`, not `sourceforge.net`

```
get_url: url=http://downloads.sourceforge.net/project/libpng/libpng16/{{ libpng_ver }}/libpng-{{ libpng_ver }}.tar.gz dest={{ magick_path }}/libpng-{{ libpng_ver }}.tar.gz
```

**Comment by acozine** [comment]
Closed when the Centos branch got merged in.
