### ISSUE TITLE
Fedora 4.6 requires modifications to JAVA_OPTS

### ISSUE THREAD

**Issue by sanfordd** [curationexperts/ansible-hydra#154]
Fedora 4.6 removes the default modeshape levelDB for Fedora. The database has to be manually listed in JAVA_OPTS.

**Comment by sanfordd** [comment]
supported-versions-expansion branch should solve this.

**Comment by acozine** [comment]
Fixed by e80289d8e0aefe58ef953fdf7e7290580b0af787
