### ISSUE TITLE
Old versions of fits break installs

### ISSUE THREAD

**Issue by sanfordd** [curationexperts/ansible-hydra#155]
The pre .0.8 versions of fits lack the fits-env.sh script. While there's not a lot of reason to use the older version, people who need to use this to reproduce old machines can run into errors. The fits-env.sh tasks should only trigger on newer versions of fits.

**Comment by sanfordd** [comment]
supported-versions-expansion branch should solve this.

**Comment by grosscol** [comment]
This is to support the Sufia 6.x installations?  The 7.x branch uses fits 0.8 and higher.  I would suggest pushing 1.x as it has commit that allows resolution of links to fits.sh and doesn't need special handling with PATH.

**Comment by acozine** [comment]
FYI, we just dialed back from fits 1.0.1 to fits 0.8.5 on a project due to intermittent fits failures on image ingests.

**Comment by acozine** [comment]
This issue fixed by e80289d8e0aefe58ef953fdf7e7290580b0af787 - I'll open a new issue for  incorporating fits 1.x soon.
