### ISSUE TITLE
Enable mod_rewrite in apache configuration

### ISSUE THREAD

**Issue by hackartisan** [curationexperts/ansible-hydra#163]
To support the capistrano/maintenance gem out of the box (see apache configuration here: https://github.com/curationexperts/ansible-hydra/blob/master/roles/webserver/config/templates/apache_ssl_config.j2#L16) we need to enable mod_rewrite during apache installation / configuration.

This will be a single play in an existing playbook, but the way this is done differs between ubuntu and centOS.

**Comment by acozine** [comment]
Closed by 4bddb8a2094ac6f45ab377980d5412331406a8b3
