### ISSUE TITLE
Postgress password issue in vagrant branch/build

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#18]
```
NOTIFIED: [services | set postgres password] ********************************** 
fatal: [default] => Missing become password

FATAL: all hosts have already failed -- aborting
```

**Comment by mark-dce** [comment]
This seems to be due to 
https://github.com/acozine/sufia-ansible/blob/master/roles/services/handlers/main.yml#L4

If I add 

```
    ansible.ask_become_pass = true
```

to my Vagrantfile somewhere near the `ansible.playbook =` line, I get prompted to supply the sudo (vagrant) password and the role and notifications run fine.

I'm not sure if it's better to prompt for the password, or try to embed it somewhere - this seems OK since the user: vagrant / password: vagrant pattern is well known.

**Comment by acozine** [comment]
To clarify for Future Me - the password ansible is seeking here is the ssh user's password, which is used to `sudo su` to the postgres user, which then resets its own password. If we refactor to use `sudo` consistently and get rid of `become`, we'll need to use `ansible.ask_sudo_pass` instead.
