### ISSUE TITLE
base_path needs a leading slash

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#20]
We need "/prod" instead of "prod" here:
https://github.com/acozine/sufia-ansible/blob/54fc6d2cb012db269af673453ddaf7251e32709e/roles/hydra-stack/defaults/main.yml#L7

**Comment by hackartisan** [comment]
resolved?

**Comment by mark-dce** [comment]
@hackmastera - yes! Sorry, you had it fixed in cap-refactor and I forgot to close the ticket.
