### ISSUE TITLE
Support multiple background-processing utilities

### ISSUE THREAD

**Issue by acozine** [curationexperts/ansible-hydra#206]
We currently support resque. Consider adding alternatives:
- [ ] sidekiq
- [ ] delayed_job
- [ ] rabbitmq

**Comment by acozine** [comment]
Changes to use sidekiq are mainly in the codebase rather than in the server setup:
- add `gem 'sidekiq'` and `gem 'capistrano-sidekiq'` to the Gemfile
- add `require "capistrano/sidekiq"` in the Capfile
- set `config.active_job.queue_adapter = :sidekiq` in `config/environments/production.rb`
- create `config/initializers/sidekiq.rb` to connect sidekiq to redis
- create `config/sidekiq.yml` to define the queues, and match the setting of the ingest queue in `config/initializers/hyrax.rb` - e.g. `config.ingest_queue_name = :ingest`
- if desired, add `require 'sidekiq/web'` and `mount Sidekiq::Web => '/sidekiq'` to `config/routes.rb` to add the sidekiq management pane

See https://github.com/curationexperts/nurax/commit/a93f77c8a77702e5fb68c6453c5d870001537451 for some of the changes described above.

**Comment by mark-dce** [comment]
Standardizing on community preferred use of `sidekiq` in https://github.com/curationexperts/ansible-samvera
