### ISSUE TITLE
Upgrade to Ansible 2.0

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#22]

**Comment by mark-dce** [comment]
Upgrade to 2.0 & Test existing playbooks:
- [ ]  create_ec2.yml
- [ ] configure.yml
- [ ] vagrant_dev.yml
- [ ] vagrant_staging.yml
- [ ] [sufia-prod-ubuntu-vagrant/vagrant-sufia-prod.yml](https://github.com/mark-dce/sufia-prod-ubuntu-vagrant/blob/master/vagrant-sufia-prod.yml#L6)

**Comment by hackartisan** [comment]
Stable release will come in January at the earliest

**Comment by acozine** [comment]
In Ansible 2.0 the variable ansible_ssh_user is deprecated - move to ansible_user instead.

**Comment by acozine** [comment]
Deprecation warnings taken care of in https://github.com/projecthydra-labs/ansible-sufia7-playbook/pull/15
