### ISSUE TITLE
set_timezone role has no effect on Ubuntu 16

### ISSUE THREAD

**Issue by acozine** [curationexperts/ansible-hydra#254]
Ubuntu 16.04 uses timedatectl instead of dpkg-reconfigure to set the time zone. See https://github.com/curationexperts/laevigata/issues/731

**Comment by mark-dce** [comment]
Possibly fixed by #256 - by letting Ansible determine the appropriate strategy to set the timezone for the specific OS

**Comment by mark-dce** [comment]
NOTE: I pulled PR #256 which is superseded by PR #259 

I've tested the new timezone role on a Vagrant based Ubuntu 16.04 system and the timezone does get set correctly by the new role:

```
vagrant@camper:~$ cat /etc/timezone 
Europe/London
vagrant@camper:~$ date
Mon Aug 28 17:27:36 BST 2017
vagrant@camper:~$ exit
logout
Connection to 127.0.0.1 closed.
MARKs-MacBook-Pro-2:camper mark$ date
Mon Aug 28 11:28:17 CDT 2017
MARKs-MacBook-Pro-2:camper mark$ 
```

**Comment by acozine** [comment]
By default Ubuntu 16 uses `timesyncd` instead of `nptd` - see https://www.digitalocean.com/community/tutorials/how-to-set-up-time-synchronization-on-ubuntu-16-04.

**Comment by bess** [comment]
Fixed in ansible-samvera
