### ISSUE TITLE
Rename to ansible-samvera ?

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#255]
**QUESTION:** Should we rename the repo?

*Discuss*

**Comment by acozine** [comment]
It would be cleaner and more modern. We should probably also update all the variable names (e.g. `samvera_db_user` instead of `hydra_db_user`). Of course, that would be backwards-incompatible.

**Comment by mark-dce** [comment]
We decided to make a new repo and migrate roles one-by-one.  https://github.com/curationexperts/ansible-samvera
