### ISSUE TITLE
Separate out (Sufia) dependencies more discretely

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#257]
I need fits and redis installed on development environments like the Samvera Camp vitural machine, but I don't need a database setup or resque (since inline now works and some folks are interested in sidkiq instead)

Also, "Sufia dependencies" is potentially an out of date name.

Would it be possible to turn all of the things these do into more discrete roles?

**Comment by acozine** [comment]
Related to #40.

**Comment by acozine** [comment]
Related to #206.
