### ISSUE TITLE
Set ssh timeout to be resilient for poor network connections

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#266]
**ISSUE**
As configured in the defaults, the ssh session timeout may cause the session to be more likely to die unexpectedly on poor network connections.  Since there are no retries, a very short network dropout at just the right time can disconnect you even when you're actively editing a file...

**CURRENT SETTINGS**
ClientAliveInterval 600
ClientAliveCountMax 0

**PROPOSED SETTINGS**
ClientAliveInterval 120
ClientAliveCountMax 5

In the proposed settings, the client would have to fail at five consecutive 2-minute checks (i.e. 10 minutes), but would remain alive if the system provides a successful response in any one of the tries.  In the original, the session dies immediately on a single check at 10 minutes with no retries.

**Comment by acozine** [comment]
The defaults were set to meet the production spec for laevigata, with only the one variable available for override:
```
 # manage inactive ssh sessions
TCPKeepAlive no
ClientAliveInterval {{ ssh_timeout }}
ClientAliveCountMax 0
```
I agree that adding a variable for the retries is a good idea. Let me noodle on this for a bit.

**Comment by mark-dce** [comment]
We may want to think about backwards compatibility and deprecation notification - i.e.

Release X implements new ssh timeout settings and deprecates use without inactivity checks
- Please set ssh_timeout to your desired value in your config values, default is 0 (to match previous builds)

Release X+1 implements a 10 minute ssh inactivity timeout
- Please explicitly set your ssh_timeout to 0 if you wish to maintain previous behavior, default is 600 seconds.

**Comment by mark-dce** [comment]
Moved to https://github.com/curationexperts/ansible-samvera
