### ISSUE TITLE
Rescue-Pool is in unknown state

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#268]
It feels like this error happens periodically.  Capturing it here in case others have a solution.  Otherwise, we should consider trying to refactor the role in a way that makes it more resilient.

```
TASK [sufia_dependencies/install : start resque] *********************************************************************************
 [WARNING]: The service (resque-pool) is actually an init script but the system is managed by systemd

fatal: [52.72.119.114]: FAILED! => {"changed": false, "failed": true, "msg": "Service is in unknown state", "status": {}}
	to retry, use: --limit @/Users/mark/Documents/workspace/_no_backup_/deploying_hydra/tufts-cm/tufts-ubuntu.retry
```

**Comment by acozine** [comment]
Thanks for including the full error message. What OS and version are you seeing this on? Is it Ubuntu 16?

**Comment by mark-dce** [comment]
OS + Version: *Welcome to Ubuntu 16.10 (GNU/Linux 4.8.0-41-generic x86_64)*

**Comment by acozine** [comment]
I'm seeing this from time to time as well. So far I can't tell what distinguishes runs where this task succeeds from those where it fails. Ultimately the answer may be to use `sidekiq` or some other background-job utility. Related to #206.

**Comment by mark-dce** [comment]
We've adopted `sidekiq` for all work going forward.
