### ISSUE TITLE
Change secret key to SECRET_KEY_BASE environment variable convention

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#29]
http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#config-secrets-yml
https://help.ubuntu.com/community/EnvironmentVariables

**Comment by mark-dce** [comment]
Ok, I'm going ahead with this ticket as is, but there's an interesting article and discussion about the potential pitfalls of storing secret_key_base in the environment:
http://movingfast.io/articles/environment-variables-considered-harmful/

It's easy enough to refactor to have ansible generate the keys and store them in the config file directly - that's the pattern for devise and blacklight keys in the current repo.

**Comment by hackartisan** [comment]
I'm in favor of the generate & store strategy. I couldn't find the pattern you mentioned used for blacklight / devise -- would love a pointer.

If we used environment variables, we would also want ansible to put that in place for the relevant user, no?

Looks like currently we are using a variable with a default. If people accept the default they're presumably making themselves vulnerable.

Might be nice to accept a variable but generate a default if it's not provided.

**Comment by mark-dce** [comment]
@hackmastera - Sorry, I didn't realize I still only had this in the **secrets** branch, the pattern I meant is here:
https://github.com/curationexperts/ansible-hydra/blob/secrets/roles/app-config/tasks/initializers.yml#L2-L4
AND
https://github.com/curationexperts/ansible-hydra/blob/secrets/roles/app-config/templates/blacklight_initializer.rb.j2

**Comment by mark-dce** [comment]
fixed in https://github.com/curationexperts/ansible-samvera
