### ISSUE TITLE
Extract FITS install from sufia-dependencies

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#30]
**ISSUE** 
FITS is a hydra-derivatives dependency and may be used by applications other than Sufia

**NOTES**
Consider renaming Sufia-dependencies or moving FITS, ImageMagick, and FFmpeg to individual roles that sufia-dependencies can depend on

**Comment by acozine** [comment]
superceded by #40, which needs additional details and/or sub-issues
