### ISSUE TITLE
Clean up FITS install

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#35]
The current FITS role copies alot of unnecessary files into /usr/local/bin

```
- name: copy fits to /usr/local/bin
  sudo: yes
  shell: cp {{ install_path }}/fits-{{ fits_version }}/* /usr/local/bin/
```

It would be nicer to just simlink to a full installation in the opt directory.  BUT... the fits.sh script doesn't do a good job of figuring out where it lives when launched as a symlink.

The other possibility would be to install fits to /opt/fits-x.y.z and just add that to the path. 

I'm not sure what the best solution is.  Possibly just leaving it as-is.

**Comment by mark-dce** [comment]
Maybe just install fits to /opt/fits.x.y.z and add the explicit path to the sufia initializer:
https://github.com/projecthydra/sufia/blob/bc9763fcc7fb6213d5a58b2f2166d747f4f5dea5/README.md#characterization

**Comment by acozine** [comment]
It's ugly, but it works for both 0.6\* and 0.8*. It will also allow us to test the FITS install in the ansible script by using FITS at the command line.
