### ISSUE TITLE
Detangle hydra dependencies from project-specific dependencies

### ISSUE THREAD

**Issue by acozine** [curationexperts/ansible-hydra#40]
## EPIC

Currently the sufia-dependencies role contains some items that non-sufia-based hydra heads might also use. For example, FITS.

Refactor to separate project-specific dependencies and make the scripts more user-friendly for installing a variety of hydra heads.

**Comment by acozine** [comment]
The sufia-dependencies role installs:
- a database
- fits
- resque
- redis

Those are all integral to running a hydra project (although redis isn't the only tool for background jobs). I propose we rename sufia-dependencies to hydra-tools, or else merge the role into the hydra-stack role. Which would folks prefer?

**Comment by sanfordd** [comment]
I'm willing to just go with a renaming since it seems like most other use cases will also need those tools.

**Comment by acozine** [comment]
We'll take care of this in conjunction with #169, so the new playbooks will reference the correct role name.

**Comment by mark-dce** [comment]
outdated and largely handled
