### ISSUE TITLE
Pin version of ffmpeg that's installed

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#43]
**ISSUE**
The current installer appears to install the latest version of FFMPEG on source forge. This might make it difficult to duplicate configurations over time if the version of FFMPEG gets updated between the time systems are built.

See https://github.com/curationexperts/ansible-hydra/blob/f77e6bdbec81925da2e7fa37aa47bc162e61b212/roles/ffmpeg/tasks/ffmpeg.yml

**OPTIONS**
1. Let ffmpeg version float as-is and close this ticket
2. Add versioning logic like imagemagick
3. Just use  the Ubunutu packaged version (need to check how out of date it is for 14.04 LTS repos)

**Comment by acozine** [comment]
I've seen issues with specific non-free libraries being left out of the ffmpeg build (esp. in the packaged versions), but I don't remember issues with version differences in ffmpeg itself. Of course we could run into issues with version changes, but I'm not aware of current or recent problems. I vote for your first solution, at least until an issue presents itself (as it most certainly did with ImageMagick).

**Comment by mark-dce** [comment]
Sold on option No. 1. Closing.
