### ISSUE TITLE
Orphan file?

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#45]
Is this file an orphan?
./roles/app-config/templates/ansible-sudoers.j2

**contents:**

```
{{ sudo_user_1 }} ALL=(ALL) NOPASSWD:ALL
{{ sudo_user_2 }}  ALL=(ALL) NOPASSWD:ALL
```

I can't find any task that references ansible-sudoers.j2 or any place that sudo_user_1 is defined.

**Comment by acozine** [comment]
Yes. I'll remove it. Not everyone wants to use passwordless sudo.
