### ISSUE TITLE
Add Comments to roles' main task

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#51]
We've decided it would be a good idea to add some basic comments to the main.yml file for each role.  Both just to help you figure out where you are, and, when, needed to help give more context about the role:

**BASIC VERSION EXAMPLE**
https://github.com/curationexperts/ansible-hydra/blob/eed11d39df4cddb9b4d3828410974c7e357c9977/roles/imagemagick/tasks/main.yml#L2-L3

**GIVES MORE CONTEXT VERSION**
https://github.com/curationexperts/ansible-hydra/blob/5957bb726bd596d01b52dba099e1335384cfe513/roles/mount_opt/tasks/main.yml#L2-L10

**ACCEPTANCE**
Add comments to the roles that are missing them:
- [x] ansible-hydra/roles/apache-passenger/config/tasks/main.yml
- [x] ansible-hydra/roles/apache-passenger/install/tasks/main.yml
- [x] ansible-hydra/roles/app-config/tasks/main.yml
- [x] ansible-hydra/roles/capistrano_setup/tasks/main.yml
- [x] ansible-hydra/roles/ec2/tasks/main.yml
- [x] ansible-hydra/roles/ffmpeg/tasks/main.yml
- [x] ansible-hydra/roles/hydra-stack/install/tasks/main.yml
- [x] ansible-hydra/roles/hydra-stack/config-capistrano/tasks/main.yml
- [x] ansible-hydra/roles/imagemagick/tasks/main.yml
- [x] ansible-hydra/roles/launch_ec2/tasks/main.yml
- [x] ansible-hydra/roles/mount_opt/tasks/main.yml
- [x] ansible-hydra/roles/openjdk1_8/tasks/main.yml
- [x] ansible-hydra/roles/packages/tasks/main.yml
- [x] ansible-hydra/roles/riiif/tasks/main.yml
- [x] ansible-hydra/roles/ruby/tasks/main.yml
- [x] ansible-hydra/roles/set_timezone/tasks/main.yml
- [x] ansible-hydra/roles/sufia_dependencies/config/tasks/main.yml
- [x] ansible-hydra/roles/sufia_dependencies/install/tasks/main.yml
- [x] ansible-hydra/roles/system_setup/tasks/main.yml
- [x] ansible-hydra/roles/vagrant_setup/tasks/main.yml

**Comment by acozine** [comment]
Last examples closed by f7c6c97f4dbfcbbed87794a3a99d4ed5e9f58afa
