### ISSUE TITLE
configure.yml playbook doesn't start apache

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#63]
I ran the playbook successfully and I appear to have fedora and solr (tomcat) running fine, but there's no web server responding on port 80.

When I try to check the service I get this:

```
$ sudo service apache2 status
apache2: unrecognized service
```

**Comment by mark-dce** [comment]
Running against the issue-44 branch (remove role-level become)

Seeing the same issue on Vagrant, so it appears to be an issue with something in the removed become instruction at the role level

**Comment by acozine** [comment]
So it sounds like ansible failed to install apache correctly? I've looked for breaking changes and I don't see any. The only oddity i see is the duplication of the 'become' setting here: https://github.com/curationexperts/ansible-hydra/blob/3f13d55a543e80b72825d04837a8f9e0570588a4/roles/apache-passenger/install/tasks/main.yml#L30-L32.

**Comment by acozine** [comment]
Closing, none of us can reproduce this one.
