### ISSUE TITLE
document the submodule pattern used in curationexperts/sufia-prod-ubuntu-vagrant

### ISSUE THREAD

**Issue by hackartisan** [curationexperts/ansible-hydra#67]
Add info on how to set this up into the README or wiki

**Comment by hackartisan** [comment]
I did this today. Here is I think how I did it!

Create private repo with your hosts file and group_vars dir. You might want to also protect these with ansible-vault.

```
$ git submodule add git@github.com:curationexperts/ansible-hydra.git
$ cd ansible-hydra/
$ git checkout desired-commit-hash
$ cd ..
```

add an ansible.cfg like

```
[defaults]
roles_path = ./ansible-hydra/roles
```

Then when you pull somewhere else

```
$ cd [your wrapper repo]
$ git submodule update --init
```

In general, read about git submodules.

How does this mesh with your experience, @mark-dce??

**Comment by mark-dce** [comment]
That sounds pretty spot on.  

```
$ git checkout desired-commit-hash -or-branch-or-tag
```

We just updated the sample vagrant file so you don't need anything in your hosts file - vagrant is going to dynamically assign an IP each time you bring up the box, so there is just an empty placeholder.  Also, I'm running without any group_vars at all.

**Comment by hackartisan** [comment]
I don't think I've used anything in my hosts file for vagrant thus far. Haven't investigated relationship between vagrant and group_vars. But we do need hosts files and group_vars to manage aws boxes! That's the primary use case for our wrapper repository. Point taken the documentation should account for both scenarios.

**Comment by hackartisan** [comment]
https://github.com/curationexperts/ansible-hydra/wiki/Use-this-project-as-a-submodule
