### ISSUE TITLE
documentation on java versions

### ISSUE THREAD

**Issue by hackartisan** [curationexperts/ansible-hydra#78]
I see this commit adds an optional role for java 8. Now I can no longer figure out how java7 is getting installed :\

ee29c138736ef9022050ce8f8e883253be5ee9e0

It might be worth some README or wiki action on how to specify a java version.

**Comment by sanfordd** [comment]
It looks like Java 7 is being installed as part of  /roles/hydra-stack/install/tasks/ tomcat.yml. Tomcat grabs Java 7 from the Ubuntu repos as a default.

**Comment by acozine** [comment]
Closing in favor of #158.
