### ISSUE TITLE
Can't generate PDF thumbnails

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#79]
The sample PDF I've been using can be downloaded here: https://raw.githubusercontent.com/mark-dce/camper/master/sample-assets/AK-Page-4.pdf

The command line I've been using to test generating a thumbnail is:

```
convert -thumbnail x300 -background white -alpha remove AK-Page-4.pdf[0] ak-thumb.png
```

**Comment by mark-dce** [comment]
This error appears to be spurious - I'm getting a working thumbnail after running this:

```
$ convert -thumbnail x300 -background white -alpha remove AK-Page-4.pdf[0] ak-thumb.png
gs: /usr/local/lib/libtiff.so.5: no version information available (required by /usr/lib/libgs.so.9)
convert: iCCP: profile 'default_rgb.icc': 0h: PCS illuminant is not D50 `/tmp/magick-5281r-DBH29RQCP31' @ warning/png.c/MagickPNGWarningHandler/1656.
```

but I get a working `ak-thumb.png`

**Comment by mark-dce** [comment]
I just built a Vagrant VM with the secrets branch (which shouldn't affect versions) and get working PDF derivatives.

Versions:
fits: 0.6.2
imagemagick: 6.9.1-10 
ghostscript: 9.10
libtiff installed from source: tiff-4.0.5.tar.gz

I still get an the error shown above when I run convert at the command line, but it produces a valid thumbnail png.

The characterization shown in Sufia is:

```
File format: pdf (Portable Document Format)
Mime type: application/pdf
File size: 179182 
Last modified: 2015:12:17 22:25:00-05:00 
Filename: AK Page 4.pdf 
Original checksum: b25b6455910dd8b2794ddb70d913d137 
Well formed: true 
Valid: true 
File title: AK Page 4 
Page count: 1 
```

If someone else can build sufia and gets proper thumbnails for the PDF, we should probably close this ticket but note the versions that work together in the wiki.

**Comment by acozine** [comment]
Issue traced back to a bad copy of the file in question - unable to reproduce with any other PDF.
