### ISSUE TITLE
Add "Danger can't undo" warning to terminate_ec2.yml playbook

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#82]
The terminate_ec2 playbook permanently deletes the instance and all volumes and data associated with it.

Add a prompt at the beginning of the playbook that requires the user to type "yes" to execute the deletion.

see http://docs.ansible.com/ansible/playbooks_prompts.html

**Comment by acozine** [comment]
Closed by #202. We may enhance this later, but for now at least it's better.
