### ISSUE TITLE
Write somewhere in system the commit of this repo used to build.

### ISSUE THREAD

**Issue by hackartisan** [curationexperts/ansible-hydra#83]
$ cat /usr/share/misc/ansible-build-info
"system built with curationexperts/ansible-hydra@271f6ea"

Open to other ideas!! But I think it would be nice to be able to check this down the line.

**Comment by acozine** [comment]
+1 - we could also include the ansible_version for good measure.

**Comment by acozine** [comment]
so, add a localhost task that executes the git command to get the hash, then register that as a variable

**Comment by acozine** [comment]
Closed by #203.
