### ISSUE TITLE
Keyfile in ansible.cfg

### ISSUE THREAD

**Issue by sanfordd** [curationexperts/ansible-hydra#85]
The line

private_key_file=/Users/alicia/.ssh/devtest.pem

In the ansible.cfg file seems to conflict with the instructions given in step 5 of the README file. Can it be removed, it generated some confusing errors.

**Comment by acozine** [comment]
Yes, it can. Thanks for trying out the scripts @sanfordd. I added that default for my own use and forgot about it. Fix should be in master later today.
