### ISSUE TITLE
tomcat / solr config seem mixed-up / nonexistent

### ISSUE THREAD

**Issue by hackartisan** [curationexperts/ansible-hydra#98]
Here's my story! I built an ec2 dev box with these ansible scripts that just uses apache and tomcat, running the rails app in development mode. Happy to share my playbooks once it's a little more ironed out. It worked great until I wanted to write a test to get me started on developing a new feature. Turned out my app couldn't connect to the solr test core -- hey, there isn't one! so I needed to figure out how to add one.

It looks like I now have it working using "core discovery" [1, 2] which is this nice feature which means that all you have to do is add another directory for your new core under /opt/solr and stick a core.properties file inside it.

However it looks like /opt/solr contains this config file hydra.xml which is actually a tomcat config file [3] which should really live in /etc/tomcat/Catalina/localhost/ -- wait, it's in that directory also!! But I only see in the ansible scripts where it's placed in /opt/solr [4]; I don't see it being placed in the other location.

Also, there's no solr.xml in /opt/solr. It seems additional cores cannot be discovered unless I add a solr.xml that at least looks like 

```
<?xml version="1.0" encoding="UTF-8" ?>
<solr></solr>
```

I can submit a PR that puts such a solr.xml in that location. And I think we could remove hydra.xml from that directory. But I'm very unsure as to how that hydra.xml is getting into /etc/tomcat/Catalina/localhost since I don't see it in the ansible scripts. Also wanted to run this by @acozine in case there are Reasons for all of this which are not apparent to me.

[1] https://wiki.apache.org/solr/Solr.xml%204.4%20and%20beyond
[2] https://wiki.apache.org/solr/Core%20Discovery%20%284.4%20and%20beyond%29
[3] https://wiki.apache.org/solr/SolrTomcat#Installing_Solr_instances_under_Tomcat
[4] https://github.com/curationexperts/ansible-hydra/blob/f70906d0bf0ba44c79af7fd6140ba816e44fc7a6/roles/hydra-stack/install/tasks/solr.yml#L61

**Comment by hackartisan** [comment]
Here's where the tomcat file is put into /etc/tomcat/Catalina/localhost
https://github.com/curationexperts/ansible-hydra/blob/master/roles/hydra-stack/install/tasks/solr.yml#L65

Alicia says she likes to put it in /opt/solr because then it's easy to find all the solr-related config files.

There are also benefits across OSes.

**Comment by hackartisan** [comment]
Recommendation: Continue to keep the tomcat config file in the current location, symlink as it's done now. Add comments explaining that it's a tomcat config file, that solr itself does not use it.

Add a skeletal solr.xml into /opt/solr

**Comment by acozine** [comment]
Sorry I let this issue get so stale. @hackmastera is this still a concern with standalone solr?

**Comment by acozine** [comment]
Closing in favor of #158 for the documentation aspect. With standalone Solr, the scripts now create and configure the first core. I don't have a use case for multi-core Solr at the moment. If we come up with a use case, let's open a separate ticket.
